beam_width: 3
connector_diameter: 2
connector_spacing: 10
connector_tolerance: 1
mesh: "examples/wing.stl"
part_separation: false
printer_extents:
- 200.0
- 200.0
- 200.0
directory: "output"
name: "wing"
plane_spacing: 20
scale_factor: 50.8